---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-mcp"  (include "godon.fullname" .) | trunc 58 | quote }}
  labels:
    service-type: "mcp-endpoint"
    app.kubernetes.io/component: mcp
  {{- with .Values.mcp.service }}
  {{- if .annotations }}
  annotations:
    {{- toYaml .annotations | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  type: "ClusterIP"
  ports:
    - protocol: TCP
      name: "mcp-port"
      port: {{ .Values.mcp.port }}
      targetPort: {{ .Values.mcp.containerPort }}
  selector:
    component: mcp
    release: {{ .Release.Name }}
