## Docker Compose to enable k0s to run locally exclusively on single osuosl node

### k0s

version: "3"
services:
  kube-master:
    container_name: kube-master
    image: docker.io/k0sproject/k0s:v1.31.5-k0s.0
    command: |
      /bin/sh -c "
      rm -rf /shared/join-token.env &&
      k0s controller --config=/etc/k0s/config.yaml &
      sleep 5 &&
      mkdir -p /shared &&
      k0s token create --role=worker --expiry=1h > /shared/join-token.env &&
      wait
      "
    hostname: kube-master
    privileged: true
    restart: always
    #cgroup: host
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1g
        reservations:
          cpus: '0.5'
          memory: 500m
    volumes:
      - "kube-master-shared:/shared"
      - "kube-master:/var/lib/k0s"
      # This is just so that we get the kubeconfig file out
      - /run:/var/lib/k0s
    network_mode: "bridge"
    environment:
      K0S_CONFIG: |-
        apiVersion: k0s.k0sproject.io/v1beta1
        kind: ClusterConfig
        metadata:
          name: k0s-kube-master
        # Any additional configuration goes here ...
    tmpfs:
    - /run
    - /var/run
    ports:
      - "127.0.0.1:6443:6443"
    network_mode: "bridge"

  kube-worker-1:
    image: docker.io/k0sproject/k0s:v1.31.5-k0s.0
    container_name: kube-worker-1
    hostname: kube-worker-1
    #cgroup: host
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1g
        reservations:
          cpus: '0.5'
          memory: 500m
    privileged: true
    restart: always
    depends_on:
      - kube-master
    volumes:
      - "kube-master-shared:/shared"
      - "kube-worker-1:/var/lib/k0s"
      - "/github-runner/godon-charts/godon-charts/:/script/"
    tmpfs:
    - /run
    - /var/run
    network_mode: "bridge"
    command: /bin/sh /script/worker_join.sh

  kube-worker-2:
    image: docker.io/k0sproject/k0s:v1.31.5-k0s.0
    container_name: kube-worker-2
    hostname: kube-worker-2
    #cgroup: host
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1g
        reservations:
          cpus: '0.5'
          memory: 500m
    privileged: true
    restart: always
    depends_on:
      - kube-master
    volumes:
      - "kube-master-shared:/shared"
      - "kube-worker-2:/var/lib/k0s"
      - "/github-runner/godon-charts/godon-charts/:/script/"
    tmpfs:
    - /run
    - /var/run
    network_mode: "bridge"
    command: /bin/sh /script/worker_join.sh

volumes:
  kube-master-shared:
  kube-master:
  kube-worker-1:
  kube-worker-2:
