## Kind Config for Kubernetes Test Stack on OSUOSL runner

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: godon-1-cluster
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443
nodes:
# the control plane node config
- role: control-plane
  image: kindest/node:v1.32.1
  extraMounts:
  - hostPath: /srv/storage/
    containerPath: /srv/storage
  # port mapping for conrol plane ingress to services
  extraPortMappings:
  - containerPort: 7080
    hostPort: 7080
    listenAddress: "127.0.0.1"
    protocol: TCP
# workers
- role: worker
  image: kindest/node:v1.32.1
  extraMounts:
  - hostPath: /srv/storage/
    containerPath: /srv/storage
- role: worker
  image: kindest/node:v1.32.1
  extraMounts:
  - hostPath: /srv/storage/
    containerPath: /srv/storage
