---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-godon-causal"  (include "godon.fullname" .) | trunc 58 | quote }}
  labels:
    service-type: "causal-endpoint"
    app.kubernetes.io/component: godon-causal
  {{- with .Values.causal.service }}
  {{- if .annotations }}
  annotations:
    {{- toYaml .annotations | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  type: "ClusterIP"
  ports:
    - protocol: TCP
      name: "causal-port"
      port: {{ .Values.causal.port }}
      targetPort: {{ .Values.causal.containerPort }}
  selector:
    component: godon-causal
    release: {{ .Release.Name }}
