---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-godon-observer"  (include "godon.fullname" .) | trunc 58 | quote }}
  labels:
    service-type: "metrics-endpoint"
    app.kubernetes.io/component: godon-observer
  {{- with .Values.observer.service }}
  {{- if .annotations }}
  annotations:
    {{- toYaml .annotations | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  type: "ClusterIP"
  ports:
    - protocol: TCP
      name: "metrics-port"
      port: {{ .Values.observer.port }}
      targetPort: {{ .Values.observer.containerPort }}
  selector:
    component: godon-observer
    release: {{ .Release.Name }}
