name: "deploy to gh self-hosted runner"

on:
  workflow_dispatch:

jobs:
  deploy_godon_chart:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy Latest Chart to k3s
        run: |
          sudo kubectl apply -f charts/godon/
