name: "upgrade deployment on self-hosted runner"

on:
  workflow_dispatch:

jobs:
  deploy_godon_chart:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Upgrade to Latest Chart on Local k0s Cluster
        run: |
          helm upgrade godon ./charts/godon/ \
               --kubeconfig /run/kind_kubeconfig.yaml \
               --dependency-update \
               --create-namespace --namespace godon \
               --values ./charts/godon/osuosl_deploy_values.yml

