name: "deploy to gh self-hosted runner"

on:
  workflow_dispatch:

jobs:
  deploy_godon_chart:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch k3s cluster client config
        run: |
          kubectl config view --raw >> k3s_client_config.yaml

      - name: Cleanup Former Deployment
        run: |
          helm uninstall godon --kubeconfig k3s_client_config.yaml --wait --ignore-not-found --namespace godon

      - name: Deploy Latest Chart to k3s
        run: |
          helm install godon ./charts/godon/ --kubeconfig k3s_client_config.yaml --dependency-update --namespace godon --values ./charts/godon/osuosl_deploy_values.yml

