name: "Setup k0s as docker compose stack on osuosl runner"

on:
  workflow_dispatch:

jobs:
  setup_cluster:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup k0s cluster config
        run: |
          docker-compose -f k0s-docker-compose.yml up -d
