name: "Setup k3s as docker compose stack on osuosl runner"

on:
  workflow_dispatch:

jobs:
  setup_k3s:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch k3s cluster client config
        run: |
          docker-compose -f k3s-docker-compose.yml up -d
